Final project
Evgeniy-2000/itirod pull request #2
Opened 2020-09-09 10:38 UTC by Evgeniy-2000

2020-09-09 20:36 UTC, gmltA requested changes

2020-09-09 20:36 UTC, gmltA commented on css/style.css
> +	float: top;
Няма такой велічыні для свойства 'float'

2020-09-09 20:36 UTC, gmltA commented on css/style.css
> +	float: right;
Замест float выкарыстоўваем flex ці grid.

2020-09-09 20:36 UTC, gmltA commented on css/style.css
> +@media screen and (max-width: 1000px) {
Нешта тут не супадае...

2020-09-09 20:36 UTC, gmltA commented on css/style.css
> +		border-radius: 10px;
Навошта ў вас тыя ж значэнні паўтараюцца і ўнутры media query і ў першапачатковых стылях?

2020-09-09 20:36 UTC, gmltA commented on css/style.css
> +.start_forms_registration{
Формы па цэнтру, калі ласка.

2020-09-09 20:36 UTC, gmltA commented on css/style.css
> +.sign_in_button{
Кнопку і спасылку ў форме ці па цэнтру, ці неяк па-іншаму, але сіметрычна адносна самой формы. Тое ж самае з `input`'амі.

2020-09-09 20:36 UTC, gmltA commented on index.js
> +    const header = null || document.querySelector('header');
Гэта што за канструкцыя?

2020-09-09 20:36 UTC, gmltA commented on views/ChooseCrossword.js
> +        let temp1 = "";
Асэнсаваныя назвы зменных, калі ласка.

2020-09-09 20:36 UTC, gmltA commented on views/constructor.js
> +        Constructor.columns = 10;
У карыстальніка павінна быць магчымасць мяняць гэтыя параметры.

2020-09-09 20:36 UTC, gmltA commented on views/constructor.js
> +        let tmp = '';
Асэнсаваныя назвы, калі ласка.

2020-09-09 20:36 UTC, gmltA commented on views/constructor.js
> +        });
Гэта што за функцыя?

2020-09-09 20:36 UTC, gmltA commented on views/portfolio.js
> +            if(all[0][i].procents.indexOf(1313) >= 0) {
Гэта што за індэксы такія?

2020-09-09 20:36 UTC, gmltA commented on views/portfolio.js
> +        }
Усё гэта адрэфактарыць у больш зразумелыя функцыі са зразумелымі назвамі.

2020-09-09 20:36 UTC, gmltA commented on views/portfolio.js
> +        setTimeout(() => {
Навошта гэта?

2020-09-09 20:36 UTC, gmltA commented on views/solve.js
> +        for (var i = 0; i < 8; i++) {
Аднолькавы код выносіцца, каб не паўтараць адно і тое ж у некалькіх файлах.

2020-09-09 20:36 UTC, gmltA commented on views/solve.js
> +        finish.addEventListener('click', async e => {
Усю функцыю вынесці, адрэфактарыь і падзяліць на больш дробныя.

2020-09-09 20:36 UTC, gmltA commented on views/solver.js
> +        btnLoad.addEventListener('click', e => {
Таксама перапісаць.

2020-09-09 20:36 UTC, gmltA commented on views/solver.js
> +                setTimeout(() => {
Не патрэбен тут `setTimeout`.

2020-09-09 20:36 UTC, gmltA commented on views/solver.js
> +        btnCheck.addEventListener('click', e => {
Таксама падзяліць на больш дробныя.

2020-09-09 20:36 UTC, gmltA commented on index.js
> +    auth.onAuthStateChanged(firebaseUser => {
Чаму я магу трапіць на старонку стварэння красворда без аўтарызацыі?

2020-09-09 20:36 UTC, gmltA commented on views/ChooseCrossword.js
> +let ChooseCrossword = {
![image](https://user-images.githubusercontent.com/138737/92650479-3ea2fe00-f2f5-11ea-9ab4-d47dd13ab05b.png)
Нешта тут не так з вёрсткай...

2020-09-10 14:24 UTC, Evgeniy-2000 commented on css/style.css
> +	float: top;
Убрано

2020-09-10 14:24 UTC, Evgeniy-2000 commented on css/style.css
> +	float: right;
Изменено

2020-09-10 14:24 UTC, Evgeniy-2000 commented on css/style.css
> +@media screen and (max-width: 1000px) {
Не заметил. Изменено

2020-09-10 14:25 UTC, Evgeniy-2000 commented on css/style.css
> +		border-radius: 10px;
Копировал и вставлял кусками, чтобы поменять значение отдельных элементов, и забыл убрать лишнее

2020-09-10 14:26 UTC, Evgeniy-2000 commented on css/style.css
> +.start_forms_registration{
Сделано

2020-09-10 14:26 UTC, Evgeniy-2000 commented on css/style.css
> +.sign_in_button{
Выполнено

2020-09-10 14:31 UTC, Evgeniy-2000 commented on views/solver.js
> +                setTimeout(() => {
Здесь мы в header получаем из index.html шапку страницы, чтобы потом в неё добавить через innerHTML навигационную панель.

2020-09-10 14:32 UTC, Evgeniy-2000 commented on index.js
> +    const header = null || document.querySelector('header');
Здесь мы в header получаем из index.html шапку страницы, чтобы потом в неё добавить через innerHTML навигационную панель.

2020-09-10 14:33 UTC, Evgeniy-2000 commented on views/ChooseCrossword.js
> +        let temp1 = "";
Изменено. Более того, temp1 оказалась неиспользуемой переменной, которую забыл убрать по ошибке.

2020-09-10 14:35 UTC, Evgeniy-2000 commented on views/constructor.js
> +        let tmp = '';
Изменено

2020-09-10 14:41 UTC, Evgeniy-2000 commented on views/constructor.js
> +        });
В личном кабинете каждому кроссворду данного пользователя присвоен некий порядковый номер. Чтобы отредактировать некоторый кроссворд, необходимо ввести порядковый номер соответствующий ему. Далее, клетки таблицы (в БД хранятся в виду строки), а также прочие данные кроссворда заполняются данными из БД.

2020-09-10 14:45 UTC, Evgeniy-2000 commented on views/portfolio.js
> +            if(all[0][i].procents.indexOf(1313) >= 0) {
Извиняюсь, данный код вообще не используется в этом проекте, забыл убрать файлы portfolio.js, Answers.js, solver.js. На этапе перехода с "несколько html страниц" на "только index.html, а остальное скрипты" я брал чужие проекты, чтобы понять как организовать связь между файлами. На этапе переделывания под себя (использовался свой код), забыл убрать чужие файлы (но они работе сайта вообще никак не отражаются).

2020-09-10 14:46 UTC, Evgeniy-2000 commented on views/portfolio.js
> +        }
Неиспользуемый код, подробно расписал в комментариях выше.

2020-09-10 14:46 UTC, Evgeniy-2000 commented on views/portfolio.js
> +        setTimeout(() => {
Неиспользуемый код, подробно расписал в комментариях выше

2020-09-10 14:47 UTC, Evgeniy-2000 commented on views/solver.js
> +        btnLoad.addEventListener('click', e => {
Неиспользуемый код, подробно расписал в комментариях выше

2020-09-10 14:47 UTC, Evgeniy-2000 commented on views/solver.js
> +                setTimeout(() => {
Неиспользуемый код, подробно расписал в комментариях выше

2020-09-10 14:47 UTC, Evgeniy-2000 commented on views/solver.js
> +        btnCheck.addEventListener('click', e => {
Неиспользуемый код, подробно расписал в комментариях выше

2020-09-16 13:06 UTC, Evgeniy-2000 commented on views/ChooseCrossword.js
> +let ChooseCrossword = {
Почему-то в разных брузерах по разному отображается эта таблица. 
Изменено.

2020-09-16 13:06 UTC, Evgeniy-2000 commented on views/constructor.js
> +        Constructor.columns = 10;
Добавлена необходимая возможность

2020-09-16 13:07 UTC, Evgeniy-2000 commented on views/solve.js
> +        for (var i = 0; i < 8; i++) {
Вынесено в table.js

2020-09-16 13:08 UTC, Evgeniy-2000 commented on views/solve.js
> +        finish.addEventListener('click', async e => {
Выполнено

2020-09-17 15:21 UTC, Evgeniy-2000 commented on index.js
> +    auth.onAuthStateChanged(firebaseUser => {
Предотвращена таковая возможность.

2020-09-18 20:06 UTC, gmltA requested changes

2020-09-18 20:06 UTC, gmltA commented on index.js
> +    const header = null || document.querySelector('header');
Чаму мы проста не можам напісаць

`const header = document.querySelector('header');`?

2020-09-18 20:06 UTC, gmltA commented on views/constructor.js
> +                            cell_value = cells_inputs[i * hor_count_prev + j].value;
Я не магу змяніць колькасць слупкоў і радкоў. Памылка недзе тут.

![image](https://user-images.githubusercontent.com/138737/93640232-e9f13880-fa02-11ea-87aa-246dc776d99a.png)

2020-09-18 20:06 UTC, gmltA commented on views/ChooseCrossword.js
>  let ChooseCrossword = {
![image](https://user-images.githubusercontent.com/138737/93640405-36d50f00-fa03-11ea-96a0-ca4f891ef97a.png)


Вось так выглядае старонка ў мабільнай версіі...

2020-09-18 20:06 UTC, gmltA commented on views/navBar.js
> +                    <a href="" id="exit">Exit</a>
`a` без валіднага `href` не павінна існаваць.

2020-09-18 21:06 UTC, Evgeniy-2000 commented on views/navBar.js
> +                    <a href="" id="exit">Exit</a>
Изменено.

2020-09-18 21:08 UTC, Evgeniy-2000 commented on views/ChooseCrossword.js
>  let ChooseCrossword = {
Я запускал у себя с такими же параметрами разрешения - всё было нормально. Однако, когда я ширину увеличил на 1 пиксель, получилось примерно тоже, что и в вашем случае. Было решено в style.css подогнать размерность экрана для мобильных устройств под 380px.

2020-09-18 21:10 UTC, Evgeniy-2000 commented on index.js
> +    const header = null || document.querySelector('header');
Оказывается, можем. Если такового элемента не найдётся - само по себе вернётся значения null.

2020-09-18 21:14 UTC, Evgeniy-2000 commented on views/constructor.js
> +                            cell_value = cells_inputs[i * hor_count_prev + j].value;
Было достаточно в 191-й строке поменять местами "i" и "j".

2020-09-20 09:17 UTC, gmltA requested changes
![image](https://user-images.githubusercontent.com/138737/93707908-042e3200-fb3b-11ea-8c20-1c58e0a255de.png)

Усё яшчэ не падобна на мабільную версію.

І распішыце, калі ласка, як мне стварыць красворд. Я запісаў пытанні, націскнуў «Save», але нічога не адбылося...

2020-09-20 23:21 UTC, Evgeniy-2000 commented
> 
> 
> ![image](https://user-images.githubusercontent.com/138737/93707908-042e3200-fb3b-11ea-8c20-1c58e0a255de.png)
> 
> Усё яшчэ не падобна на мабільную версію.
> 
> І распішыце, калі ласка, як мне стварыць красворд. Я запісаў пытанні, націскнуў «Save», але нічога не адбылося...

1) По поводу сохранения: если оставить хотя бы одно из полей "Name", или "Id" пустым, то сохранения не произойдёт. Теперь, если попытаться оставить какое-то поле пустым - будет отображено уведомление.
2) По поводу вёрстки: подскажите, пожалуйста, как вы получили подобное? Потому что у меня на разрешении 375х812 все хорошо. Пробовал более низкие по ширине разрешения - всё равно не получил что-то похожее на ваш случай.

2020-09-21 11:45 UTC, gmltA reviewed
Я проста выстаўляю эмуляцыю iPhone X у Chrome.

Пакажыце, як у вас гэта выглядае.

2020-09-21 12:07 UTC, Evgeniy-2000 commented
> 
> 
> Я проста выстаўляю эмуляцыю iPhone X у Chrome.
> 
> Пакажыце, як у вас гэта выглядае.

Я через Firefox открываю
![изображение](https://user-images.githubusercontent.com/58752510/93764632-1af88580-fc1c-11ea-8691-17f3ab710533.png)

2020-09-21 12:35 UTC, gmltA commented
Глядзіце на хроме, бо мабільная версія Firefox працуе не так, як сапраўдныя мабільныя браўзеры.

2020-09-22 15:56 UTC, Evgeniy-2000 commented
> Глядзіце на хроме, бо мабільная версія Firefox працуе не так, як сапраўдныя мабільныя браўзеры.

Здравствуйте! Переделали под хром.
На всякий случай скрин того, как это отображается у меня:
![image](https://user-images.githubusercontent.com/58752510/93906308-b6652580-fd04-11ea-9393-7b607d2c631d.png)

2020-09-23 14:35 UTC, gmltA approved these changes
Добра. Дастаткова. Поспехаў.

2020-09-23 14:47 UTC, merged